services:
  backend:
    build: ./backend
    container_name: demo-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: demo-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"