apiVersion: v1
kind: Service
metadata:
  name: po-lin-postgresql-service
  namespace: demo-po-lin
spec:
  selector:
    app: po-lin-postgresql
  ports:
    - name: postgresql-port
      port: 5432
      targetPort: 5432