apiVersion: v1
kind: Service
metadata:
  name: po-lin-redis-service
  namespace: demo-po-lin
spec:
  selector:
    app: po-lin-redis
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379