apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-lin-redis
  namespace: demo-po-lin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po-lin-redis
  template:
    metadata:
      labels:
        app: po-lin-redis
    spec:
      containers:
      - name: redis-container
        image: redis:latest
        ports:
        - containerPort: 3000
          protocol: TCP
