apiVersion: v1
kind: Service
metadata:
  name: po-lin-result-service
  namespace: demo-po-lin
spec:
  selector:
    app: po-lin-result
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
