apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-lin-worker
  namespace: demo-po-lin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po-lin-worker
  template:
    metadata:
      labels:
        app: po-lin-worker
    spec:
      containers:
      - name: worker-container
        image: barberry/worker:latest
        env:
          - name: REDIS_HOST
            value: po-lin-redis-service
          - name: REDIS_PORT
            value: "6379"
          - name: DB_HOST
            value: po-lin-postgresql-service
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: postgres
          - name: DB_NAME
            value: postgres
