apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-lin-vote
  namespace: po-lin-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po-lin-vote
  template:
    metadata:
      labels:
        app: po-lin-vote
    spec:
      containers:
      - name: redis-container
        image: po-lin/lab-vote:1.0
        ports:
        - containerPort: 3000
          protocol: TCP
